### ISSUE TITLE
configurable tile buffer

### ISSUE THREAD

**Issue by ARolek** [terranodo/tegola#107]
One of the issues being reported during geometry clipping (#56) is a rendering fragment due to the lack of tile buffer. Vector tiles use a "hack" where the tile buffer extends beyond the tile extent. This allows for a smooth transition between tiles. An example of the issue can be seen in the attached screenshot.
![fa79546e-1b6a-11e7-966e-656cbec01aec](https://cloud.githubusercontent.com/assets/667850/24871316/0ef0d77c-1dce-11e7-80e2-0e6b29e99ff7.png)

**Comment by sagarr** [comment]
I hope it also solves problem like this (road cuts at adjoining tiles)

![fireshot capture 1 - - http___localhost_8080_index html 16 39_49 58995_6 14185](https://user-images.githubusercontent.com/1051004/33139840-69570642-cfd4-11e7-9c53-e9826a80f648.png)

**Comment by gdey** [comment]
Yes, I would say those issues are related to the title buffer. The buffer is not big enough.

**Comment by gdey** [comment]
I no longer think the issue is because of the tile buffer is not big enough. I think this has to do with bounding boxes removing 
I no longer think it's because the tile buffer is not big enough. I think this has to do with the geometries we are grabbing before clipping. These geometries are the ones within a bounding box defined by the z/x/y tile. We then expand that bounding box the buffer size and clip the geometries to that new bounding box. Unfortunately, this means we don't grab all possible geometries that could be there in the newly expanded bounding box. (The Purple geometries in the figure.) I believe this is leading to the jagged edges we see as alluded to by [this StackOverflow post](https://stackoverflow.com/questions/40466547/vector-tiles-buffer). 
![explain_107](https://user-images.githubusercontent.com/14805/33532062-cba5ed4e-d84a-11e7-991f-01b4d6b02ada.png)

What we should be doing is expanding the bounding box by the buffer, and grab all the geometries in that new bounding box. We just clip to that bounding box as well.

**Comment by gdey** [comment]
Anyone have an isolated dataset for this issue? I think I have a solution; that I need to test.

**Comment by sagarr** [comment]
@gdey Do you have a solution on github branch which I can pull from? I want to test it.

**Comment by gdey** [comment]
@sagarr Not yet, I'll push up as soon as I have figured out this bug, then ping you.

**Comment by gdey** [comment]
@sagarr I just pushed up a branch called issue-107. Please try that branch out. I still have a few failing tests there, and some clean up to do. 

But you should be able to test it.

**Comment by ARolek** [comment]
This issue has been merged into the v0.6.0 branch and will be included in the next release. You can give it a test by pulling down the branch and building from source.
