### ISSUE TITLE
Add Feature Provider intended to deprecate/replace mvt.Provider.

### ISSUE THREAD

**Issue by JivanAmara** [terranodo/tegola#182]
There's currently provider.go, provider/*, mvt/provider/*.
These should be consolidated.

**Comment by ARolek** [comment]
We're talking about removing the mvt.Provider interface and creating a FeatureProvider interface. Pushing the responsibility of encoding MVT layers onto the provider is an old decision we want to go away. Providers should only be responsible for returning geometries and their associated tags.

**Comment by JivanAmara** [comment]
What are you thinking for communicating the relationship of layers to features in a FeatureProvider?

**Comment by ARolek** [comment]
Quick design we're playing with. Still settling on the names but this is the main idea:

```go
type tegola.Feature{
  geom geom.Geometry
  tags map[string]interface{}
}

type FeatureProvider interface {
  FeaturesByBounds(ctx context.Context, layerName string, bounds Bounds) []tegola.Feature
}
```

**Comment by gdey** [comment]
I guess I'm highjacking this issue and turing it into a quick discussion about the Feature Provider. I want to make sure we have a good design before we start work on this. 

Two Points:

1. Should Tegola.Feature have an SRID field? Or should each feature return have a way to get the SRID? This is needed as I think the responsibility for converting to a desired srid should fall at the layer level. The other thing related to to this that I comes up is to have an field in the FeaturesByBounds that acts like a hint, for the srid.

2. Bounds here is not quite the same as a bounding box. We need the X,Y,Z values and the bounding box. Or At least the SRID that the bounding box being provided is in. Currently, because the providers are handling the mvt layer, they calculate the bound box from the X,Y,Z and a hard coded resolution conversion for the Z. However, there are some problems with this and so we need to rethink this a bit.

**Comment by ARolek** [comment]
An additional point is that the feature providers should know what zoom they're dealing with as we have a !ZOOM! token to support.

**Comment by JivanAmara** [comment]
@gdey, are there any examples of features within a layer being encoded with different srid's?  I haven't seen it in gpkg's but the srid of a feature's geometry is stored independently of the layer's claimed srid so the possibility is there at least for this provider.

**Comment by gdey** [comment]
I have not seen it. The main reason is that the SRID needs to be provided, currently we are returning at slice of features. The Alternative is to return an SRID a long with the slice.:
```
type FeatureProvider interface {
  FeaturesByBounds(ctx context.Context, layerName string, bounds Bounds) (features []tegola.Feature,srid int)
}
```

**Comment by ARolek** [comment]
After thinking this over a bit more, I'm going to propose we name the method `TileFeatures` since the tile will come with the Z, X and Y values as well as helper methods `BoundingBox` and the upcoming `BufferedBoundingBox` which the provider should be using to address the issue described in #107 . 

Updated proposed interface:

```go
type FeatureProvider interface {
  TileFeatures(ctx context.Context, layerName string, tile tegola.Tile) ([]tegola.Feature, error)
}
```

Regarding the SRID, features from a query should all have the same SRID otherwise they would not match the BoundingBox query. Additionally, I believe @gdey is proposing that the geom.Geometry interface have an SRID() method so each feature would know it's own SRID. So it's technically possible for a slice of features to have different SRIDs, but highly unlikely.

**Comment by JivanAmara** [comment]
POC at https://github.com/terranodo/tegola/tree/issue-182_new_provider_interface
Managed to implement FeatureProvider interface with minor changes to each of:
 * MVTLayer->TileFeatures
 * layerFromQuery->featuresFromQuery
 * NewProvider->NewFeatureProvider

and types/interfaces in provider/featureProvider.go
Not sure exactly how you guys would want to access NewFeatureProvider to try things out, since it returns a different type (FeatureProvider instead of mvt.Provider) I can't just drop it in for provider.Register()
