### ISSUE TITLE
Get the intersected geometry by pg

### ISSUE THREAD

**Issue by exotfboy** [terranodo/tegola#277]
Hi:

I found that the feature are selected by from the database only filtered by the `bbox` by default(unless you set your own sql in the confituration), and then clip the geometry by the `bbox`(with a padding) again by program.

There is no problem for points and simple line or polygon feature.

However if the geometry of the feature is too big, this may take a long time, think about a very large and complex reservoirs which may contains 100K nodes,then every tile request which cover this feature will get the complete geometry from the database. So I wonder why do not use the `ST_Intersection` function by pg to generate a clipped geometry?

**Comment by ARolek** [comment]
@exotfboy you're correct, we're handling the geo processing (clipping, simplification, etc.) via tegola and not in PostGIS. We went this route as not all data providers  (i.e. goejson, geopackage, shapefiles, etc.) have the tooling that PostGIS comes with. In order to position tegola so it can support additional data providers tegola needs the geo processing tools. 

This considered, you're correct that large features will take a data transfer hit as they're carried over the wire between PostGIS and tegola, but the geo processing hit still needs to happen somewhere. Right now the processing hit happens on tegola rather than at PostGIS. Pros and cons to both approaches. 

We could implement ST_Intersection for the PostGIS data provider as a possible optimization, but the data transfer form PostGIS to tegola should generally not be too large, even with 100k nodes. One of the early steps of processing a polygon in tegola is dropping nodes outside of the clip region at the same time we're making the polygon valid. This minimizes the processing necessary and will continue to improve as the algorithm matures via profiling and optimization.

**Comment by exotfboy** [comment]
Thank you for your attention. This does make sense once we try to support more data sources.And you are right there must be somewhere the intersection occur which may take a lot of resources like CPU or memory.
