### ISSUE TITLE
Caching at higher levels than specified by maxZoom 

### ISSUE THREAD

**Issue by ear7h** [terranodo/tegola#311]
From what I understand [here](https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Zoom_levels) higher zooms correspond with higher numbers. However the code in the `filecache` and `s3cache` packages assume the opposite, not caching when the zoom level is lower than `MaxZoom`.

```go
// inside Set() method

//	check for maxzoom
if fc.MaxZoom != nil && key.Z <= int(*fc.MaxZoom) {
	return nil
}

// do cache
```

Also, I think mechanism is makes odd use of pointers and uint types. I'm willing to change this but wanted to submit an issue for clarification.

**Comment by ARolek** [comment]
@ear7h you're correct about "lower zooms" being closer to zero, and this looks like a bug. Thanks for reporting it. I will add a test case to both the `filecache` and `s3cache` and get this fixed.

Regarding the uint / pointer piece being odd, I agree. This is because some of the typing is going through a transition. Tile requests come to tegola in the format of `/:map_name/:z/:x/:y`. Currently we parse the z/x/y values into `int` values, but then we hit a bug with invalid requests of negative values. You can see the checking happening [here](https://github.com/terranodo/tegola/blob/master/server/handle_map_zxy.go#L51). The plan is to convert everything to `uint` values and drop the less than zero checking. This will also require an update to the cache interface and then some code cleanup to the various cache implementations. I will open another issue to track it.

**Comment by ear7h** [comment]
Okay sounds good. I'll look for those tests when you submit them and make corresponding ones for the `rediscache`

**Comment by ARolek** [comment]
@ear7h my recent PR (https://github.com/terranodo/tegola/pull/314) has the max_zoom fix and associated tests. Thanks again for the report. Teach me to not write test cases... ;-)
